name: generate

on:
  # on new push
  push:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned
  # everyday at 12pm
  schedule:
    - cron: "0 12 * * *"

jobs:
  generate:
    concurrency:
      group: issues
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
      - name: cache tools
        id: tools
        uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: ts-graphviz/setup-graphviz@v1
      - run: cd misc/deps; make install
      - run: go install -v ./gen-graph

      - run: make fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make gen-json
      - run: make gen-image

      - run: git rm -f .gitignore
      - run: git add output/
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_pattern: 'output/*'
          commit_message: "build: generate"
          branch: generate
          push_options: '--force'
          create_branch: true
          commit_user_name: gnobot
          commit_user_email: actions@github.com
          commit_author: gnobot 🤖 <actions@github.com>
